" Default vim path ini all versions
set rtp +=~/.vim

" vim plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

" Helper conditional install bundle
function! Cond(cond, ...)
  let opts = get(a:000, 0, {})
  return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

call plug#begin('~/.vim/plugged')
    if filereadable(expand('~/.bundlerc'))
        for fpath in split(globpath('~/dotfiles/vim/bundles', '*.vim'), '\n')
          exe 'source' fpath
        endfor

        source ~/.bundlerc
    endif
call plug#end()

for fpath in split(globpath('~/dotfiles/vim/settings', '*.vim'), '\n')
  exe 'source' fpath
endfor

" map <silent> <leader>li :set list!<bar>set nolist?<cr>
" map <silent> <leader><cr> :set hls!<bar>set nohls?<cr>

vnoremap <silent> <CR> "+y

" Spell
set spellcapcheck=[.?!]\_[\])'"^I ]\+
map <silent> \pt :set spell spelllang=pt<cr>
map <silent> \en :set spell spelllang=en<cr>
map <silent> \ns :set nospell<cr>

map <silent> \ns :set nospell<cr>

" When pressing <leader>cd switch to the directory of the open buffer
map <silent><leader>cd :cd %:p:h<CR>:pwd<CR>
" map <leader>cd :exec ":cd expand(%:p:h)"<CR>

" trim
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun

map <silent>\tr :call <SID>StripTrailingWhitespaces()<CR>

" Shortcuts for nav tabs
map \bo :e<Space>
noremap <silent><cr> :b#<cr>
map <silent> <Tab> :bn<CR>
map <silent> <S-Tab> :bp<CR>


" vim:noet:foldmethod=marker
