# Customize
DISABLE_AUTO_TITLE="true"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export LS_COLORS="ow=01;30;42"

# Nord theme
export FZF_DEFAULT_OPTS='
    --color fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C
    --color pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#81A1C1,marker:#EBCB8B
'

export VISUAL=nvim
export EDITOR="$VISUAL"

export PATH=~/dotfiles/bin:$PATH:~/bin
