# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize
DISABLE_AUTO_TITLE="true"

export PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
