# Customize
DISABLE_AUTO_TITLE="true"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export LS_COLORS="ow=07;32;40"

export VISUAL=nvim
export EDITOR="$VISUAL"

export PATH=~/dotfiles/bin:$PATH:~/bin
